// Code generated by "stringer -type=Stage"; DO NOT EDIT.

package stage

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-0]
	_ = x[Check-1]
	_ = x[Create-2]
	_ = x[Upload-3]
	_ = x[Delete-4]
}

const _Stage_name = "InputCheckCreateUploadDelete"

var _Stage_index = [...]uint8{0, 5, 10, 16, 22, 28}

func (i Stage) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Stage_index)-1 {
		return "Stage(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Stage_name[_Stage_index[idx]:_Stage_index[idx+1]]
}
